import { verificationSchema, bulkJobSchema } from "./verification-schema";

export const mockVerifications = [
  {
    id: "1",
    email: "john.doe@example.com",
    result: "Valid" as const,
    quality: "Good",
    type: "Personal",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 10:30 AM",
  },
  {
    id: "2",
    email: "support@company.com",
    result: "Valid" as const,
    quality: "Excellent",
    type: "Corporate",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 10:25 AM",
  },
  {
    id: "3",
    email: "invalid@fake-mail.com",
    result: "Invalid" as const,
    quality: "Poor",
    type: "Unknown",
    suggestion: "Do not send",
    credits: 1,
    date: "2025-01-15 10:20 AM",
  },
  {
    id: "4",
    email: "risky@temp-mail.com",
    result: "Risky" as const,
    quality: "Fair",
    type: "Temporary",
    suggestion: "Use with caution",
    credits: 1,
    date: "2025-01-15 10:15 AM",
  },
  {
    id: "5",
    email: "alice@example.com",
    result: "Valid" as const,
    quality: "Excellent",
    type: "Personal",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 10:10 AM",
  },
  {
    id: "6",
    email: "bob@company.org",
    result: "Valid" as const,
    quality: "Good",
    type: "Corporate",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 10:05 AM",
  },
  {
    id: "7",
    email: "spam@bad-domain.com",
    result: "Invalid" as const,
    quality: "Poor",
    type: "Unknown",
    suggestion: "Do not send",
    credits: 1,
    date: "2025-01-15 10:00 AM",
  },
  {
    id: "8",
    email: "test@disposable.com",
    result: "Risky" as const,
    quality: "Fair",
    type: "Temporary",
    suggestion: "Use with caution",
    credits: 1,
    date: "2025-01-15 09:55 AM",
  },
  {
    id: "9",
    email: "jane@example.io",
    result: "Valid" as const,
    quality: "Excellent",
    type: "Personal",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 09:50 AM",
  },
  {
    id: "10",
    email: "info@business.com",
    result: "Valid" as const,
    quality: "Good",
    type: "Corporate",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 09:45 AM",
  },
  {
    id: "11",
    email: "fake@test-mail.com",
    result: "Invalid" as const,
    quality: "Poor",
    type: "Unknown",
    suggestion: "Do not send",
    credits: 1,
    date: "2025-01-15 09:40 AM",
  },
  {
    id: "12",
    email: "temp@10minutemail.com",
    result: "Risky" as const,
    quality: "Fair",
    type: "Temporary",
    suggestion: "Use with caution",
    credits: 1,
    date: "2025-01-15 09:35 AM",
  },
  {
    id: "13",
    email: "contact@website.com",
    result: "Valid" as const,
    quality: "Excellent",
    type: "Corporate",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 09:30 AM",
  },
  {
    id: "14",
    email: "user@domain.net",
    result: "Valid" as const,
    quality: "Good",
    type: "Personal",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 09:25 AM",
  },
  {
    id: "15",
    email: "invalid@nonexistent.com",
    result: "Invalid" as const,
    quality: "Poor",
    type: "Unknown",
    suggestion: "Do not send",
    credits: 1,
    date: "2025-01-15 09:20 AM",
  },
  {
    id: "16",
    email: "marketing@startup.com",
    result: "Valid" as const,
    quality: "Excellent",
    type: "Corporate",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 09:15 AM",
  },
  {
    id: "17",
    email: "sales@enterprise.io",
    result: "Valid" as const,
    quality: "Good",
    type: "Corporate",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 09:10 AM",
  },
  {
    id: "18",
    email: "noreply@spammy.com",
    result: "Invalid" as const,
    quality: "Poor",
    type: "Unknown",
    suggestion: "Do not send",
    credits: 1,
    date: "2025-01-15 09:05 AM",
  },
  {
    id: "19",
    email: "test@guerrillamail.com",
    result: "Risky" as const,
    quality: "Fair",
    type: "Temporary",
    suggestion: "Use with caution",
    credits: 1,
    date: "2025-01-15 09:00 AM",
  },
  {
    id: "20",
    email: "hello@creative.agency",
    result: "Valid" as const,
    quality: "Excellent",
    type: "Personal",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 08:55 AM",
  },
  {
    id: "21",
    email: "webmaster@site.org",
    result: "Valid" as const,
    quality: "Good",
    type: "Corporate",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 08:50 AM",
  },
  {
    id: "22",
    email: "bounce@fake.com",
    result: "Invalid" as const,
    quality: "Poor",
    type: "Unknown",
    suggestion: "Do not send",
    credits: 1,
    date: "2025-01-15 08:45 AM",
  },
  {
    id: "23",
    email: "admin@tech.co",
    result: "Valid" as const,
    quality: "Excellent",
    type: "Corporate",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 08:40 AM",
  },
  {
    id: "24",
    email: "support@helpdesk.net",
    result: "Valid" as const,
    quality: "Good",
    type: "Corporate",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 08:35 AM",
  },
  {
    id: "25",
    email: "mailer@tempinbox.com",
    result: "Risky" as const,
    quality: "Fair",
    type: "Temporary",
    suggestion: "Use with caution",
    credits: 1,
    date: "2025-01-15 08:30 AM",
  },
  {
    id: "26",
    email: "dev@software.io",
    result: "Valid" as const,
    quality: "Excellent",
    type: "Personal",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 08:25 AM",
  },
  {
    id: "27",
    email: "info@platform.app",
    result: "Valid" as const,
    quality: "Good",
    type: "Corporate",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 08:20 AM",
  },
  {
    id: "28",
    email: "invalid@throwaway.com",
    result: "Invalid" as const,
    quality: "Poor",
    type: "Unknown",
    suggestion: "Do not send",
    credits: 1,
    date: "2025-01-15 08:15 AM",
  },
  {
    id: "29",
    email: "founder@startup.xyz",
    result: "Valid" as const,
    quality: "Excellent",
    type: "Personal",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 08:10 AM",
  },
  {
    id: "30",
    email: "team@collaboration.work",
    result: "Valid" as const,
    quality: "Good",
    type: "Corporate",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 08:05 AM",
  },
  {
    id: "31",
    email: "no-reply@bulkmail.biz",
    result: "Risky" as const,
    quality: "Fair",
    type: "Temporary",
    suggestion: "Use with caution",
    credits: 1,
    date: "2025-01-15 08:00 AM",
  },
  {
    id: "32",
    email: "customer@service.com",
    result: "Valid" as const,
    quality: "Excellent",
    type: "Corporate",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 07:55 AM",
  },
  {
    id: "33",
    email: "partner@network.io",
    result: "Valid" as const,
    quality: "Good",
    type: "Corporate",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 07:50 AM",
  },
  {
    id: "34",
    email: "spam@fake-mail.biz",
    result: "Invalid" as const,
    quality: "Poor",
    type: "Unknown",
    suggestion: "Do not send",
    credits: 1,
    date: "2025-01-15 07:45 AM",
  },
  {
    id: "35",
    email: "office@company.co.uk",
    result: "Valid" as const,
    quality: "Excellent",
    type: "Corporate",
    suggestion: "Safe to send",
    credits: 1,
    date: "2025-01-15 07:40 AM",
  },
];

export const mockBulkJobs = [
  {
    id: "1",
    fileName: "customer_list.csv",
    status: "Completed" as const,
    totalEmails: 500,
    processedEmails: 500,
    validEmails: 450,
    invalidEmails: 50,
    createdAt: "2025-01-15 09:00 AM",
  },
  {
    id: "2",
    fileName: "newsletter_subscribers.csv",
    status: "Processing" as const,
    totalEmails: 1000,
    processedEmails: 675,
    validEmails: 600,
    invalidEmails: 75,
    createdAt: "2025-01-15 10:00 AM",
  },
  {
    id: "3",
    fileName: "prospect_list.csv",
    status: "Completed" as const,
    totalEmails: 250,
    processedEmails: 250,
    validEmails: 220,
    invalidEmails: 30,
    createdAt: "2025-01-14 03:30 PM",
  },
  {
    id: "4",
    fileName: "failed_batch.csv",
    status: "Failed" as const,
    totalEmails: 100,
    processedEmails: 0,
    validEmails: 0,
    invalidEmails: 0,
    createdAt: "2025-01-14 02:00 PM",
  },
];

export const verificationsData = mockVerifications.map((v) => verificationSchema.parse(v));
export const bulkJobsData = mockBulkJobs.map((j) => bulkJobSchema.parse(j));
